services:
  mailmate:
    build:
      context: ./.
      target: mailmate
    ports:
      - "3000:3000"
    command: npm run dev
    restart: unless-stopped
    volumes:
      - "./:/home/node/.:ro"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
